### ISSUE TITLE
Infografía equipohjf

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/infografia-de-las-librerias-JoseABCruz#2]
José Antonio Balbuena Cruz
Ingeniería en Sistemas Computacionales
4° Semestre
[Librerias.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-JoseABCruz/files/8211182/Librerias.pdf)

**Comment by OFELHER93** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
